-- Setup: Create database, schema, and warehouse
CREATE DATABASE IF NOT EXISTS DB_ONTOLOGY_CONTROL_PLANE;
CREATE SCHEMA IF NOT EXISTS DB_ONTOLOGY_CONTROL_PLANE.SAP_PRODUCTION;
CREATE WAREHOUSE IF NOT EXISTS ONTOLOGY_WH
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE;

USE DATABASE DB_ONTOLOGY_CONTROL_PLANE;
USE SCHEMA SAP_PRODUCTION;
USE WAREHOUSE ONTOLOGY_WH;
